server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-music
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotify-dev
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://localhost:8761/eureka