server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:    
    gateway:      
      discovery:
        locator:
          enabled: true
      routes:
        - id: msplaylist
          uri: lb://api-playlist
          predicates:
            - Path=/api/v1/playlists/**
        - id: msmusic
          uri: lb://api-music
          predicates:
            - Path=/api/v1/musics/**

info:
  app:
    name: ${spring.application.name}

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway